"""empty message

Revision ID: 8f148a7ff767
Revises: f747086d0517
Create Date: 2025-04-10 10:54:19.772308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8f148a7ff767'
down_revision: Union[str, None] = 'f747086d0517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('content')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
